[Types]
# NAME  NUMBER    GEOTYPE  EPSILON  SIGMA    ATTRACTION_DIST   ATTRACTION_SWITCH PATCH_ANGLE PATCH_SWITCH   SC_LENGTH   Paralel EPS
A       1         SPN      1.0      3.0      
B       2         SPA      1.0      1.0      1.12              0.3
[Molecules]
# Molecules letter
#  bond1 - harmonic bond between nearest neighbours
#  bond2 - harmonic bond between second nearest neighbours
#  angle1 - angle between two spherocylinders -nearest neighbours
#  angle2 - angle between two spherocylinder patches -nearest neighbours
#  particles - types as they go in chain in molecule
A: {
#what:       TYPE     SWITCHTYPE  DELTA_MU
particles:   1
particles:   2
bond1: 10.0 3.0
angle1: 10.0 0.0
}
[System]
A 58
