#!/bin/bash

function print {
    if [ $? -eq 0 ]
    then
        echo -e $1 " \e[1;32mOK\e[0m."
    else 
        echo -e $1 " \e[1;31mNOK\e[0m."
    fi
}

function clean {
    rm -f *config.last *stat.dat *energy.dat SC a.out
    cd ../..
}

module add mpich

cd ../scOOP/

rm -f CMakeCache.txt
rm -rf CMakeFiles/

echo "Building MPI..."

cmake . -DTESTING=ON -DENABLE_MPI=ON -DENABLE_OPENMP=OFF  > /dev/null

make -j4  > /dev/null
mv SC ../Tests/

cd ../Tests/

echo ""
echo "Building comparison version for MPI..."
cd scOOP/

rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake . -DTESTING=ON -DENABLE_MPI=ON -DENABLE_OPENMP=OFF > /dev/null

make -j4 > /dev/null
mv SC ../a.out
cd ..

echo ""
echo "testing..., Warning will take cca 10 minutes"

#
# TEST normal
#
cp SC mpiTest/normal/new/
cp a.out mpiTest/normal/new/
cd mpiTest/normal/new
mpirun -np 4 ./a.out  > /dev/null

mv 0config.last 00config.last
mv 1config.last 11config.last
mv 2config.last 22config.last
mv 3config.last 33config.last

mpirun -np 4 ./SC  > /dev/null
diff 0config.last 00config.last > /dev/null
print "1) MPI Test, TCPSC, 0config.last"
diff 1config.last 11config.last > /dev/null
print "1) MPI Test, TCPSC, 1config.last"
diff 2config.last 22config.last > /dev/null
print "1) MPI Test, TCPSC, 2config.last"
diff 3config.last 33config.last > /dev/null
print "1) MPI Test, TCPSC, 3config.last"
clean
cd ..

rm -f a.out SC

echo ""
echo -e "\e[0mdone"
