#!/bin/bash

function print {
    if [ $? -eq 0 ]
    then
        echo -e $1 " \e[1;32mOK\e[0m."
    else 
        echo -e $1 " \e[1;31mNOK\e[0m."
    fi
}

function clean {
    rm -f config.last config.last2 a.out SC
}

cd ../scOOP/

rm -f CMakeCache.txt
rm -rf CMakeFiles/

echo "Building..."

cmake . -DTESTING=ON > /dev/null

make -j4 > /dev/null
mv SC ../Tests/

cd ../Tests/

echo ""
echo "Building comparison version..."
cd scOOP/

rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake . -DTESTING=ON > /dev/null

make -j4 > /dev/null
mv SC ../a.out
cd ..

echo ""
echo "testing..., warning: this could take up to 10 minutes"

for name in `ls -d test_*`; do
    cp SC $name/new/
    cp a.out $name/new/
    cd $name/new
    ./a.out >/dev/null
    mv config.last config.last2
    ./SC > /dev/null
    diff config.last config.last2 > /dev/null
    print $name
    clean
    cd ../..
done

cp SC a.out volumeChange/
cd volumeChange
for name in `ls -d ?h ?l`; do
    cp SC $name/new/
    cp a.out $name/new/
    cd $name/new
    ./a.out >/dev/null
    mv config.last config.last2
    ./SC > /dev/null
    diff config.last config.last2 > /dev/null
    print $name
    clean
    cd ../..
done
cd ..

rm -f a.out SC

#./testMPI

