#!/bin/bash

function print {
    if [ $? -eq 0 ]
    then
        echo -e $1 " \e[1;32mOK\e[0m."
    else 
        echo -e $1 " \e[1;31mNOK\e[0m."
    fi
}

function clean {
    rm -f config.last SC
    cd ../old/
    rm -f  a.out config.last
    cd ../..
}

cd ../scOOP/

rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake .

make
mv SC ../Tests/

cd ../Tests/

echo ""
echo "Building comparison version..."
gcc sc35.c -O3 -march=native -msse2 -mfpmath=sse -lm

echo ""
echo "testing..."

#
# TEST normal
#
cp SC normal/new/
cp a.out normal/old/
cd normal/old
echo 'OLD'
time ./a.out >/dev/null
cd ../new/
echo 'NEW'
time ./SC > /dev/null
diff config.last ../old/config.last > /dev/null
print "1) Basic Test, TCPSC"
clean

#
# TEST chain
#
cp SC chain/new/
cp a.out chain/old/
cd chain/old
echo 'OLD'
time ./a.out > /dev/null
cd ../new/
echo 'NEW'
time ./SC > /dev/null
diff config.last ../old/config.last > /dev/null
print "2) Chain Test, 5 TCPSC"
clean

#
# TEST mempore
#
cp SC mempore/new/
cp a.out mempore/old/
cd mempore/old
echo 'OLD'
time ./a.out > /dev/null
cd ../new/
echo 'NEW'
time ./SC > /dev/null
diff config.last ../old/config.last > /dev/null
print "3) Mempore Test, pressure xy, wanglandau pore, chainmove, SPN-SPA-SPA"
clean

#
# TEST wallfibril
#
cp SC wallfibril/new/
cp a.out wallfibril/old/
cd wallfibril/old
echo 'OLD'
time ./a.out > /dev/null
cd ../new/
echo 'NEW'
time ./SC > /dev/null
diff config.last ../old/config.last > /dev/null
print "4) WallFibril Test, external wall, switchmove, CPSC"
clean

#
# TEST pscthrough
#
cp SC pscthrough/new/
cp a.out pscthrough/old/
cd pscthrough/old
echo 'OLD'
time ./a.out > /dev/null
cd ../new/
echo 'OLD'
time ./SC > /dev/null
diff config.last ../old/config.last > /dev/null
print "5) PSC-through Test, pressure xy, wanglandau z-direct, chainmove, SPN-SPA-SPA, CPSC"
clean

rm -f a.out SC

echo ""
echo -e "\e[0mdone"