[Types]
# NAME  NUMBER    GEOTYPE  EPSILON  SIGMA  ATTRACT_DIST ATTRACT_SWITCH  PATCH_ANGLE PATCH_SWITCH  SC_LENGTH  (Optional second patch: PATCH_ROTATION PATCH_ANGLE PATCH_SWITCH )CHIRAL_ANGLE
mem_head 1        SPN      1.0       0.95
mem_tail 2        SPA      1.0       1.0   1.12246205        1.6
prot1    3        CPSC     1.0       1.0   1.12246205        1.0           170.0        5.0           4   
[Molecules]
# Molecules letter
#  bond1 - harmonic bond between nearest neighbours
#  bond2 - harmonic bond between second nearest neighbours
#  particles - types as they go in chain in molecule
A: {
#what:       TYPE     SWITCHTYPE  DELTA_MU
particles:   3
}
B: {
bond1: 90.0 0.4
bond2: 10 4.0
particles: 1
particles: 2
particles: 2
}
[System]
A  1
B 250
