[Types]
# NAME  NUMBER    GEOTYPE  EPSILON  SIGMA    ATTRACTION_DIST   ATTRACTION_SWITCH PATCH_ANGLE PATCH_SWITCH   PATCH_LENGTH   CHIRAL_ANGLE
mem_head 1        SPN        1.0     0.95
mem_tail 2        SPA        1.0     1.0        1.12246205           1.6
prot1    3       CPSC        1.0     1.0        1.12246205           1.0            170.0        5.0            6.0 0.0

[Molecules]
A: {
particles: 3
}

B: {
bond1:    90.0   0.4
bond2:    10.0   4.0
particles: 1
particles: 2
particles: 2
}

[System]
A 1
B 200
