[Types]
# NAME  NUMBER    GEOTYPE  EPSILON  SIGMA  ATTRACT_DIST ATTRACT_SWITCH PATCH_ANGLE PATCH_SWITCH SC_LENGTH  PARALLEL_EPS  (Optional second patch: PATCH_ROTATION PATCH_ANGLE PATCH_SWITCH )CHIRAL_ANGLE
ran_cl  1         CPSC     1.4       1.0    1.12246205        1.0          80.0        5.0         6           0.0
beta    2         CHCPSC   3.5       1.0    1.12246205        1.0         170.0        5.0         6           0.0         10
[Molecules]
# Molecules letter
#  bond1 - harmonic bond between nearest neighbours
#  bond2 - harmonic bond between second nearest neighbours
#  particles - types as they go in chain in molecule
A: {
#what:       TYPE     SWITCHTYPE  DELTA_MU
particles:   1        2           15
}
[System]
A 400
[EXTER]
# THICKNESS  EPSILON   ATTRACTION_SWITCH
5.0        4.00      1.0