[Types]
# NAME  NUMBER    GEOTYPE  EPSILON  SIGMA ATTRACT_DIST ATTRACT_SWITCH PATCH_ANGLE PATCH_SWITCH SC_LENGTH PARALLEL_EPS  (Optional second patch: PATCH_ROTATION PATCH_ANGLE PATCH_SWITCH )CHIRAL_ANGLE
A       1         SPN    1.333333  1.2 
[Molecules]
# Molecules letter
#  bond1 - harmonic bond between nearest neighbours
#  bond2 - harmonic bond between second nearest neighbours
#  angle1 - angle between two spherocylinders -nearest neighbours
#  angle2 - angle between two spherocylinder patches -nearest neighbours
#  particles - types as they go in chain in molecule
A: {
#what:       TYPE     SWITCHTYPE  DELTA_MU
particles:   1
}
[System]
A 38
