[Types]                                                                                                                                                       
# NAME  NUMBER    GEOTYPE  EPSILON  SIGMA    ATTRACTION_DIST   ATTRACTION_SWITCH PATCH_ANGLE PATCH_SWITCH   PATCH_LENGTH  CHIRAL_ANGLE                        
LipH   1         SPN      1        0.95     
LipT   2         SPA      1        1.00      1.12246205        1.6
[Molecules]                                                                                                                                                   
# Molecules letter                                                                                                                                            
#  bond1 - harmonic bond between nearest neighbours                                                                                                           
#  bond2 - harmonic bond between second nearest neighbours                                                                                                    
#  particles - types as they go in chain in molecule                                                                                                          
A: {                                                                                                                                                          
#what:       TYPE     SWITCHTYPE  DELTA_MU                                                                                                                    
bond1: 90.0 0.4
bond2: 10 4.0
particles:   1 
particles:   2                                                                                                                                                
particles:   2                                                                                                                                                
}                                                                                                                                                             
[System]                                                                                                                                                      
A 500                                                                                                                                                           


